### ISSUE TITLE
Newsfeed Portal Container

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#101]
#### sidebar
- [x] header
- [x] navigation

#### feed section (controlled by container state)
- [x] title
- [x] team feed component
- [x] chingu news feed || recent team activity feed component

#### other
- [X]  add route to switch
- [x] define state

**Comment by the-vampiire** [comment]
considerations for state

newsfeed: ALL | Team

toggleNewsFeed() -> sets state for `newsfeed`

**Comment by the-vampiire** [comment]
<FeedComponent variables={this.state.newsfeed} />

<Query query={getNewsFeed} variables={this.props.variables}>
</Query>

**Comment by luoto** [comment]
Resolves #104
