### ISSUE TITLE
Chingu News Component

### ISSUE THREAD

**Issue by luoto** [luoto/chingu-frontend#104]
child of #78
Presentational component - Renders Chingu news

**Comment by luoto** [comment]
![Screenshot 2018-08-23 15.30.12.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a85ee363e81ac0012197b2c/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc64167f3e7b57e37a25cbb078f1132943434d0eee1e020a17b8eb8339a3e43922d85c03e8823e5a77c13e11acb9d64aed06b920885d99a4fedb1294b7607caddecd5d340c041083fe5836a5994dcb5df243e14f56b65e.png)

**Comment by serpient** [comment]
forgot to do this in this branch. its in the #101 branch (=.=)
