### ISSUE TITLE
Submission video: Welcome-to-Chingu community component

### ISSUE THREAD

**Issue by tropicalchancer** [luoto/chingu-frontend#122]
**Purpose**
After reviewing the other regional winner videos and discussions with Vamper, it seems advantageous to not only say that our project submission is bringing together people from X-number of countries to collaborate, but to also show this. 

Luckily, we have lots of video content we can use. I put together a mockup video to give everyone an idea. Vamp's dad (aka one of chingu's part-time strategists ;p ) also viewed the other regional winner videos and suggested we use the content to **start** the video. 

**Here is the** [mockup of this component of the submission video.](https://youtu.be/23B9IJ0JqaM) 🌍 

It includes: 
- super short clips of people welcoming others to chingu
- 19 people/clips  
- 13 countries & flags for each country 🎏 
- time: 58 seconds

**Questions for the team:**
(feel free to answer as many or little as you like, but feedback would definitely be appreciated 🙏 )

- Do you think we should start the submission video with the Welcome to Chingu clips? If not, another place or not at all?
- Does it feel powerful to see so many people from different countries and languages welcoming others to chingu? Mainly thinking from the judges perspective for this
- If we go with this, how many clips should we use? (aka how long should this section take up)
- Any ideas for edits to improve the video? (I'll continue to edit but I'm by no means skilled ad video editing so open to all suggestions)

**Comment by the-vampiire** [comment]
i think 20-30 seconds is the right size.
we can cut back on the video lengths for people so its only them saying 'welcome to chingu'. 
you could also try speeding up the rate by 10-25% (faster enough to buy us a few seconds but not so much to make a bunch of chipmunks lol)

any way to make the flags more prominent and centered?

**Comment by WorldOfCode22** [comment]
I agree with a slight increase of speed and making it about 30 secounds. I showed it to my mom and dad for opinions one thing my dad suggested if you can chance is to put the names of the countries under the flags. We are use to all these flag and have a good idea of what most of them are, however, this may not be the best assumption for many people. I also would try to limit the clip length as much as possible without losing the point. So we can get as many clips as reasonable. I do think this would be super powerful at the very start of the video. The first thing a judge sees is people all over the world welcoming them to chingu. I still get warm and fuzzy after watching it like 5 times.

**Comment by tropicalchancer** [comment]
Got the intro to 30 seconds!
- trimmed each video to only have a hello and/or welcoming message (keep in mind some are saying welcome in their native language)
- sped up clips by 15%
- removed 5 clips (4/5 with flags we already had represented in the video)
- made the flags more prominent and in the middle

[30 second version here](https://youtu.be/OR2QX13qiw4)

I'll mockup a version with country names now too to see how that looks :)
