### ISSUE TITLE
single source for route paths / comps

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#284]
/src root level

format:
```js
routes: {
  landing: {
    path: PATH,
    component: COMPONENT
  },
 ...
}
```

**Comment by the-vampiire** [comment]
usage

`render={( { ... }) => routes.landing.component(...props) }`

**Comment by thinktwice13** [comment]
This will not work for classes

They need to be called as `props => <routes.landing.component {...props}/>` or use a wrapper on export `export default props => <Component {...props}/>`

Which one is preferred?

Branch: https://github.com/luoto/chingu-frontend/tree/feature/%23284-routes-registry
