### ISSUE TITLE
clear cache on logout

### ISSUE THREAD

**Issue by thinktwice13** [luoto/chingu-frontend#49]
child of #48

`client.cache.reset()` and `history.push("/")` cause a state update error

**Comment by WorldOfCode22** [comment]
I am not in a position to check code. I am with my mom at her doctors appointment. Are you sure the command is client.cache.reset(). I was thinking it was client.resetStore(). This link may or may not help. https://www.apollographql.com/docs/react/advanced/caching.html#reset-store

**Comment by thinktwice13** [comment]
As far as I understand. .resetStore does nothing but referch all queries. I
might be wrong and I'm also not sure about .cache.reset(), but if you just
got a notification from GitHub, that's because I was playing around with
waffle.
Sorry about that. No rush. Take care of your mom.

**Comment by WorldOfCode22** [comment]
From Apollo docs “This will cause the store to be cleared and all active queries to be refetched” So reset store should do both clear the store and active queries. However Apollo docs are always a....... interesting adventure.

**Comment by thinktwice13** [comment]
Adventure is a good word for those docs :)

Anyway,  .resetStore() worked with window.location="/", but with history.push("/") it throws a gq auth header error before I could check if the store was cleared. 

Maybe defining the query in resolvers.Query and blocking it in case of no token would help, but, at the moment, client.cache.reset() actually clears the store and redirects okay (although throwing a state transition error. Working on that now)
