### ISSUE TITLE
github team repo activity Query Def

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#72]
- queries for
  - timestamps
  - issues
  - PRs
  - activities

**Comment by tropicalchancer** [comment]
@jdmedlock built a tool for extracting metrics from Github. I'll post it here just in case it helps or saves time: 

https://github.com/jdmedlock/GitAClue

https://github.com/jdmedlock/voyageevents

https://github.com/jdmedlock/voyagemetrics
