### ISSUE TITLE
Team Standup View Component

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#73]
child of #79
child of #78

renders the team standup details as a card

**Comment by the-vampiire** [comment]
![Screen Shot 2018-08-21 at 11.48.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a04be24bf3d81001222cbfd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f26b7191a379ee0c2f59415e47bc21254d58eeb9cb74fce36f34985619e883680d26c63514ffeb871cb802ba208a1bd0e4bb894cc3fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e54455ad143560ee74326e0a.png)

**Comment by the-vampiire** [comment]
standups can be incomplete if they have null values for all of the following fields:
```
progress_sentiment: StandupSentimentEnum
worked_on: String
working_on: String
blocked_on: String
```
should we design a "has not yet completed standup" version of the standup component? or should we just ignore those and only show completed ones in the feed? @serpient

**Comment by the-vampiire** [comment]
standups can be marked as missed by checking the `is_expired` boolean on Standups (adding in next API PR)

**Comment by serpient** [comment]
we should probably only show completed ones.
