### ISSUE TITLE
Newsfeed Sidebar Component

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#77]
child of #101

state change buttons:
- all news (default view)
- teams
  - sort by status: active (top) followed by created date

set state on Newsfeed Container based on choice to control what is rendered

**Comment by the-vampiire** [comment]
[Uploading Screen Shot 2018-08-22 at 2.40.18 AM.png...]

**Comment by serpient** [comment]
Take a look at #87, i started it out by hooking up the sidebar to a query that looks for the users teams. and has styling updates too.
