### ISSUE TITLE
Team Activity  Component

### ISSUE THREAD

**Issue by the-vampiire** [luoto/chingu-frontend#79]
child of #81

## renders
maps over newsfeed(team_activity) query data array
- switch on the `newsfeed_item_type`
- return corresponding newsfeed item component (wrapped in newsfeed item component)
  - team standup view component
  - github activity component

**Comment by the-vampiire** [comment]
![Screen Shot 2018-08-22 at 2.37.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a04be24bf3d81001222cbfd/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f16b7191a37af1112c4f5f5f5edd3c4a4356bcbbd671f3e57862804e0ebfd43f0d74ce3842ffbd8118bc01ba21df1ad7b1bf8a4fd2f42f67b6d5db1063474f4dcbed5727a19041c95df54fe84c5cac103464e3722431.png)

**Comment by luoto** [comment]
child of #81
